FROM debian:buster-slim
ARG DEBIAN_FRONTEND=noninteractive
COPY entrypoint-mosquitto.sh openwb-docker-install-mosquitto.sh copy_config_back.sh /
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN /openwb-docker-install-mosquitto.sh
ENTRYPOINT ["/entrypoint-mosquitto.sh"]

