version: "3"

services:
  openwb:
    image: thelongandonly/openwb:latest
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    container_name: openwb
    network_mode: host
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      TZ: "Europe/Berlin"
      WEB_PORT: 8888
    tmpfs:
      - /var/www/html/openWB/ramdisk
    volumes:
      - ./openwb.conf:/var/www/html/openWB/openwb.conf
      - ./logdata:/var/www/html/openWB/web/logging/data

